In [43]:
#ISMET OKAN CELIK CWID:10472265
import numpy as np
import scipy.io as io
from scipy.stats import multivariate_normal

hw3_1 = io.loadmat("hw3.mat")['hw3_1']
hw3_1=np.array(hw3_1)

In [44]:
#First Iteration
r=0.5
group1_initial=np.array(hw3_1[:,1:50])
group2_initial=np.array(hw3_1[:,50:100])

mu1_initial=np.average(group1_initial,axis=1)
mu2_initial=np.average(group2_initial,axis=1)

print('mu1 = ',mu1_initial,'\n')
print('mu2 =',mu2_initial,'\n')

coVar1_initial=np.cov(group1_initial)
coVar2_initial=np.cov(group2_initial)

print('CoVarience-1 Initial = \n',coVar1_initial,'\n')
print('CoVarience-2 Initial = \n',coVar2_initial,'\n')

mu1 =  [ 0.57861074 -0.61479585] 

mu2 = [ 1.90664303 -1.4084691 ] 

CoVarience-1 Initial = 
 [[ 3.44145458 -0.99205996]
 [-0.99205996  2.3351705 ]] 

CoVarience-2 Initial = 
 [[ 6.48819951 -3.87355209]
 [-3.87355209  7.53049786]] 



In [45]:
def Grouping_Samples(mu1,mu2,coVar1,coVar2):
    p1x=[]
    p2x=[]

    group1x=[]
    group1y=[]

    group2x=[]
    group2y=[]

    for i in range(len(hw3_1[0])):
        p1x_1=multivariate_normal.pdf((hw3_1[0][i],hw3_1[1][i]),mu1,coVar1)
        p2x_1=multivariate_normal.pdf((hw3_1[0][i],hw3_1[1][i]),mu2,coVar2)
        p1x.append(p1x_1)
        p2x.append(p2x_1)

        if p1x_1>p2x_1:
            group1x.append(hw3_1[0][i])
            group1y.append(hw3_1[1][i])
        else:
            group2x.append(hw3_1[0][i])
            group2y.append(hw3_1[1][i])

    group1=[group1x,group1y]
    group1=np.array(group1)

    group2=[group2x,group2y]
    group2=np.array(group2)

    print('1.Group - After Iteration \n','1.Group Size =', len(group1x),'\n',group1,'\n')
    print('2.Group - After Iteration \n','2.Group Size =',len(group2x),'\n',group2) 
    return group1, group2

group1_1,group2_1=Grouping_Samples(mu1_initial,mu2_initial,coVar1_initial,coVar2_initial)

1.Group - After Iteration 
 1.Group Size = 69 
 [[-0.07280088  1.05258506  0.98835463  1.88607911  0.64503959 -1.4075694
   0.22241739  0.51124172 -0.29582477 -1.2408886   0.36304512 -0.14280838
   0.48402588  0.17954332 -1.84019711  0.17508785 -1.73775678  0.42687685
   0.63072796 -0.52549616  0.11000148  2.7717897  -0.54601861 -0.51018619
  -0.67263183  1.55037514 -0.56957388 -0.77150889  1.47664356 -0.06529303
  -0.09636058  0.02004178 -1.40482247 -1.41439532 -0.39017065 -0.10795249
  -1.54793297  0.51976803 -0.86742511  1.29508774 -0.37809549 -0.75926747
  -0.15479834 -1.83368706 -0.37510895  0.69696425  0.33876937 -0.74735831
  -0.64337203  0.20614694  0.74133575 -0.8001315  -0.27819611  0.22963163
  -1.17378862  1.34580337  1.23757378  0.42948853 -2.37793385  1.78266764
  -1.04415392  0.13073343  1.08837363 -0.76561454 -0.56079457  0.52128414
   0.81239961  0.77914846  0.6540751 ]
 [-0.99430985  0.42878377 -0.59901663 -0.21997506 -1.30991937 -1.90613084
   1.87132281 -1.19911652 

In [46]:
#Second Iteration

def mu_coVar(group1,group2):
    mu1=np.average(group1,axis=1)
    mu2=np.average(group2,axis=1)

    print('mu1 and mu2 After Iteration')
    print('mu1 = ',mu1)
    print('mu2 =',mu2,'\n')

    coVar1=np.cov(group1)
    coVar2=np.cov(group2)

    print('CoVarience-1 After Iteration = \n',coVar1,'\n')
    print('CoVarience-2 After Iteration = \n',coVar2,'\n')
    return mu1,mu2,coVar1,coVar2

mu1_2,mu2_2,coVar1_2,coVar2_2=mu_coVar(group1_1,group2_1)
group1_2,group2_2=Grouping_Samples(mu1_2,mu2_2,coVar1_2,coVar2_2)

mu1 and mu2 After Iteration
mu1 =  [-0.02633025 -0.18691758]
mu2 = [ 4.04606658 -2.85953061] 

CoVarience-1 After Iteration = 
 [[0.98798035 0.10837464]
 [0.10837464 0.75580288]] 

CoVarience-2 After Iteration = 
 [[ 3.55217359 -1.26990855]
 [-1.26990855  9.74971699]] 

1.Group - After Iteration 
 1.Group Size = 69 
 [[-0.07280088  1.05258506  0.98835463  1.88607911  0.64503959 -1.4075694
   0.22241739  0.51124172 -0.29582477 -1.2408886   0.36304512 -0.14280838
   0.48402588  0.17954332 -1.84019711  0.17508785 -1.73775678  0.42687685
   0.63072796 -0.52549616  0.11000148 -0.54601861 -0.51018619 -0.67263183
   1.55037514 -0.56957388 -0.77150889  1.47664356 -0.06529303 -0.09636058
   0.02004178 -1.40482247 -1.41439532 -0.39017065 -0.10795249 -1.54793297
   1.34483916  0.51976803 -0.86742511  1.29508774 -0.37809549 -0.75926747
  -0.15479834 -1.83368706 -0.37510895  0.69696425  0.33876937 -0.74735831
  -0.64337203  0.20614694  0.74133575 -0.8001315  -0.27819611  0.22963163
  -1.17378862  1

In [47]:
#Third Iteration
mu1_3,mu2_3,coVar1_3,coVar2_3=mu_coVar(group1_1,group2_1)
group1_3,group2_3=Grouping_Samples(mu1_3,mu2_3,coVar1_3,coVar2_3)

mu1 and mu2 After Iteration
mu1 =  [-0.02633025 -0.18691758]
mu2 = [ 4.04606658 -2.85953061] 

CoVarience-1 After Iteration = 
 [[0.98798035 0.10837464]
 [0.10837464 0.75580288]] 

CoVarience-2 After Iteration = 
 [[ 3.55217359 -1.26990855]
 [-1.26990855  9.74971699]] 

1.Group - After Iteration 
 1.Group Size = 69 
 [[-0.07280088  1.05258506  0.98835463  1.88607911  0.64503959 -1.4075694
   0.22241739  0.51124172 -0.29582477 -1.2408886   0.36304512 -0.14280838
   0.48402588  0.17954332 -1.84019711  0.17508785 -1.73775678  0.42687685
   0.63072796 -0.52549616  0.11000148 -0.54601861 -0.51018619 -0.67263183
   1.55037514 -0.56957388 -0.77150889  1.47664356 -0.06529303 -0.09636058
   0.02004178 -1.40482247 -1.41439532 -0.39017065 -0.10795249 -1.54793297
   1.34483916  0.51976803 -0.86742511  1.29508774 -0.37809549 -0.75926747
  -0.15479834 -1.83368706 -0.37510895  0.69696425  0.33876937 -0.74735831
  -0.64337203  0.20614694  0.74133575 -0.8001315  -0.27819611  0.22963163
  -1.17378862  1

In [48]:
#Fourth Iteration
mu1_4,mu2_4,coVar1_4,coVar2_4=mu_coVar(group1_3,group2_3)
group1_4,group2_4=Grouping_Samples(mu1_4,mu2_4,coVar1_4,coVar2_4)

mu1 and mu2 After Iteration
mu1 =  [-0.04701069 -0.15653233]
mu2 = [ 4.09209725 -2.9271623 ] 

CoVarience-1 After Iteration = 
 [[0.90005565 0.15072992]
 [0.15072992 0.82114884]] 

CoVarience-2 After Iteration = 
 [[ 3.36088921 -0.94952495]
 [-0.94952495  9.22119259]] 

1.Group - After Iteration 
 1.Group Size = 70 
 [[-0.07280088  1.05258506  0.98835463  1.88607911  0.64503959 -1.4075694
   0.22241739  0.51124172 -0.29582477 -1.2408886   0.36304512 -0.14280838
   0.48402588  0.17954332 -1.84019711  0.17508785 -1.73775678  0.42687685
   0.63072796 -0.52549616  0.11000148 -0.54601861 -0.51018619 -0.67263183
   1.55037514 -0.56957388 -0.77150889  1.47664356 -0.06529303 -0.09636058
   0.02004178 -1.40482247 -1.41439532 -0.39017065 -0.10795249 -1.54793297
   1.34483916  0.51976803 -0.86742511  1.29508774 -0.37809549 -0.75926747
  -0.15479834 -1.83368706 -0.37510895  0.69696425  0.33876937 -0.74735831
  -0.64337203  0.20614694  0.74133575 -0.8001315  -0.27819611  0.22963163
  -1.17378862  1

In [53]:
#Fifth Iteration
mu1_5,mu2_5,coVar1_5,coVar2_5=mu_coVar(group1_4,group2_4)
group1_5,group2_5=Grouping_Samples(mu1_5,mu2_5,coVar1_5,coVar2_5)

#Estimated Ro
r=len(group1_5[0])/len(hw3_1[0])
print('\n Estimated Ro Number=',r)

mu1 and mu2 After Iteration
mu1 =  [-0.03337176 -0.1204447 ]
mu2 = [ 4.19824334 -3.10372111] 

CoVarience-1 After Iteration = 
 [[0.90003279 0.18299919]
 [0.18299919 0.90041034]] 

CoVarience-2 After Iteration = 
 [[ 3.11546112 -0.38126181]
 [-0.38126181  8.53947848]] 

1.Group - After Iteration 
 1.Group Size = 71 
 [[-0.07280088  1.05258506  0.98835463  1.88607911  0.64503959 -1.4075694
   0.22241739  0.51124172 -0.29582477 -1.2408886   1.67767837  0.36304512
  -0.14280838  0.48402588  0.17954332 -1.84019711  0.17508785 -1.73775678
   0.42687685  0.63072796 -0.52549616  0.11000148 -0.54601861 -0.51018619
  -0.67263183  1.55037514 -0.56957388 -0.77150889  1.47664356 -0.06529303
  -0.09636058  0.02004178 -1.40482247 -1.41439532 -0.39017065 -0.10795249
  -1.54793297  1.34483916  0.51976803 -0.86742511  1.29508774 -0.37809549
  -0.75926747 -0.15479834 -1.83368706 -0.37510895  0.69696425  0.33876937
  -0.74735831 -0.64337203  0.20614694  0.74133575 -0.8001315  -0.27819611
   0.22963163 -1